### ISSUE TITLE
step2_train_nodule_detector.py   ValueError: output of generator should be a tuple

### ISSUE THREAD

**Issue by louiskoo520** [juliandewit/kaggle_ndsb2017#11]
![image](https://user-images.githubusercontent.com/4961164/28054006-e063d51a-6645-11e7-951c-1bc97118a436.png)

**Comment by juliandewit** [comment]
I cannot run the debugger but do you have traindata in place ?

**Comment by louiskoo520** [comment]
Thanks.I just place wrong place.  Besides why file trained_model.rar cannot download ?

**Comment by juliandewit** [comment]
Please try again..
It seems to work now.
[https://retinopaty.blob.core.windows.net/ndsb3/trained_models.rar](https://retinopaty.blob.core.windows.net/ndsb3/trained_models.rar)

**Comment by louiskoo520** [comment]
I cannot generate file model_luna16_full__fs_best.hd5.
Traceback (most recent call last):
  File "D:/Python/code/Kaggle/Bowl2017/place2-2/step3_predict_nodules.py", line 353, in <module>
    predict_cubes("models/model_luna16_full__fs_best.hd5", CONTINUE_JOB, only_patient_id=only_patient_id, magnification=magnification, flip=False, train_data=True, holdout_no=None, ext_name="luna16_fs")
  File "D:/Python/code/Kaggle/Bowl2017/place2-2/step3_predict_nodules.py", line 188, in predict_cubes
    model = step2_train_nodule_detector.get_net(input_shape=(CUBE_SIZE, CUBE_SIZE, CUBE_SIZE, 1), load_weight_path=model_path)
  File "D:\Python\code\Kaggle\Bowl2017\place2-2\step2_train_nodule_detector.py", line 345, in get_net
    model.load_weights(load_weight_path, by_name=False)
  File "C:\ProgramData\Anaconda2\envs\anaconda3\lib\site-packages\keras\engine\topology.py", line 2566, in load_weights
    f = h5py.File(filepath, mode='r')
  File "C:\ProgramData\Anaconda2\envs\anaconda3\lib\site-packages\h5py\_hl\files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\ProgramData\Anaconda2\envs\anaconda3\lib\site-packages\h5py\_hl\files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1482647201869\work\h5py\_objects.c:2866)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1482647201869\work\h5py\_objects.c:2824)
  File "h5py\h5f.pyx", line 76, in h5py.h5f.open (C:\Minonda\conda-bld\h5py_1482647201869\work\h5py\h5f.c:2112)
OSError: Unable to open file (Unable to open file: name = 'models/model_luna16_full__fs_best.hd5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by juliandewit** [comment]
I cannot run the debugger but do you have the trained model in place ?

**Comment by louiskoo520** [comment]
In step4_train_submissions , variable 'extension' is assigned at this:
      for extension in extensions:
            src_dir = settings.NDSB3_NODULE_DETECTION_DIR + "predictions" + str(int(magnification * 10)) + extension + "/"
                pred_nodules_df = pandas.read_csv(src_dir + patient_id + ".csv")
                pred_nodules_df = pred_nodules_df[pred_nodules_df["diameter_mm"] > 0]
                pred_nodules_df = pred_nodules_df[pred_nodules_df["nodule_chance"] > nodule_th]
                pred_df_list.append(pred_nodules_df)



Traceback (most recent call last):
  File "D:/Python/code/Kaggle/Bowl2017/step4_train_submissions.py", line 397, in <module>
    combine_nodule_predictions(None, train_set=False, nodule_th=0.7, extensions=[model_variant])
  File "D:/Python/code/Kaggle/Bowl2017/step4_train_submissions.py", line 130, in combine_nodule_predictions
    target_path = settings.BASE_DIR + "xgboost_trainsets/" "train" + extension + ".csv" if train_set else settings.BASE_DIR + "xgboost_trainsets/" + "submission" + extension + ".csv"
UnboundLocalError: local variable 'extension' referenced before assignment

**Comment by louiskoo520** [comment]
dicom raw data must have to include stage2 with this code ?
I find you use file combine_nodule_predictions.csv in function 'combine_nodule_predictions'?
